# Generated by Django 5.2.4 on 2025-07-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="owner",
        ),
    ]
